package com.example.demo;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/foodsApi")
public class Test {

    @GetMapping
    public List<Item> test(){
        var item1 = Item.builder()
                .id(1)
                .title("Seeds of Change Organic Red Rice")
                .store("NestFood")
                .price(Price.builder()
                        .price(32.80)
                        .discount(28.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(356)
                        .soldCount(243)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(13)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Fruit")
                .populate("Top Selling")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-1-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-1-1.jpg")
                        .build())
                .build();
        var item2 = Item.builder()
                .id(2)
                .title("All Natural Style Chicken Meatballs")
                .store("Wonderful")
                .price(Price.builder()
                        .price(122.00)
                        .discount(23.00)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(66)
                        .percentBColor("info")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Seafood")
                .populate("Top Selling")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-2-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-2-1.jpg")
                        .build())
                .build();
        var item3 = Item.builder()
                .id(3)
                .title("Angie’s Sweet & Salty Kettle Corn")
                .store("Country Crock")
                .price(Price.builder()
                        .price(52.80)
                        .discount(48.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(233)
                        .soldCount(122)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(8)
                        .percentBColor("danger")
                        .stockTime("New")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .populate("Top Selling")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-3-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-3-1.jpg")
                        .build())
                .build();
        var item4 = Item.builder()
                .id(4)
                .title("Foster Farms Takeout Crispy Classic")
                .store("Country Crock")
                .price(Price.builder()
                        .price(19.80)
                        .discount(17.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(500)
                        .soldCount(327)
                        .build())
                .salePercent(SalePercent.builder()
                        .stock("Out of Stock")
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .populate("Trending Products")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-4-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-4-1.jpg")
                        .build())
                .build();
        var item5 = Item.builder()
                .id(5)
                .title("Blue Almonds Lightly Salted Vegetables")
                .store("Country Crock")
                .price(Price.builder()
                        .price(25.80)
                        .discount(23.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(160)
                        .soldCount(141)
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Fruit")
                .populate("Top Rated")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-5-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-5-1.jpg")
                        .build())
                .build();
        var item6 = Item.builder()
                .id(6)
                .title("Chobani Complete Vanilla Greek Yogurt")
                .store("Country Crock")
                .price(Price.builder()
                        .price(55.80)
                        .discount(54.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(300)
                        .soldCount(67)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(2)
                        .percentBColor("info")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Fruit")
                .populate("Top Rated")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-6-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-6-1.jpg")
                        .build())
                .build();
        var item7 = Item.builder()
                .id(7)
                .title("Haagen Caramel Cone Ice Cream Boxed")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(24.80)
                        .discount(22.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(120)
                        .soldCount(86)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(8)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .populate("Trending Products")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-10-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-10-1.jpg")
                        .build())
                .build();
        var item8 = Item.builder()
                .id(8)
                .title("Gorton’s Beer Battered Fish Fillets")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(25.80)
                        .discount(23.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(600)
                        .soldCount(312)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(8)
                        .percentBColor("warning")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Seafood")
                .populate("Trending Products")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-9-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-9-1.jpg")
                        .build())
                .build();
        var item9 = Item.builder()
                .id(9)
                .title("Encore Seafoods Stuffed Alaskan")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(37.80)
                        .discount(35.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(350)
                        .soldCount(125)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(6)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Clothing & beauty")
                .populate("Top Rated")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-8-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-8-1.jpg")
                        .build())
                .build();
        var item10 = Item.builder()
                .id(10)
                .title("Canada Dry Ginger Ale – 2 L Bottle")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(33.80)
                        .discount(32.85)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(350)
                        .soldCount(41)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(3)
                        .percentBColor("info")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-7-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-7-1.jpg")
                        .build())
                .build();
        var item11 = Item.builder()
                .id(11)
                .title("Dried fruit: apricots, figs, prunes")
                .store("USA Noodle Soup")
                .price(Price.builder()
                        .price(76.00)
                        .discount(56.00)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(500)
                        .soldCount(234)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(27)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-11-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-11-1.jpg")
                        .build())
                .build();
        var item12 = Item.builder()
                .id(12)
                .title("Frozen fruit strawberry, berries")
                .store("Maruchan Ramen")
                .price(Price.builder()
                        .price(98.00)
                        .discount(78.00)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(150)
                        .soldCount(111)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(21)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Fresh Fruit")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-13-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-13-1.jpg")
                        .build())
                .build();
        var item13 = Item.builder()
                .id(13)
                .title("Naturally Flavored Cinnamon Vanilla")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(55.00)
                        .discount(51.00)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(220)
                        .soldCount(199)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(8)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Deals Of The Day")
                .populate("Recently Added")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-15-2.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/02/product-15-1.jpg")
                        .build())
                .build();
        var item14 = Item.builder()
                .id(14)
                .title("Seeds of Change Organic Watermelon")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(66.00)
                        .discount(61.50)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(230)
                        .soldCount(143)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(7)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .populate("Recently Added")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-1-min.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-2-min.jpg")
                        .build())
                .build();
        var item15 = Item.builder()
                .id(15)
                .title("Pre-portioned, low-fat ice cream yogurt")
                .store("Maruchan Ramen")
                .price(Price.builder()
                        .price(99.00)
                        .discount(79.00)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(120)
                        .soldCount(90)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(21)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Bread and Juice")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-4-min.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-3-min.jpg")
                        .build())
                .build();
        var item16 = Item.builder()
                .id(16)
                .title("Organic Cage Grade A Large Eggs")
                .store("Hambger Hel")
                .price(Price.builder()
                        .price(24.00)
                        .discount(21.00)
                        .build())
                .soldCount(SoldCount.builder()
                        .totalCount(400)
                        .soldCount(213)
                        .build())
                .salePercent(SalePercent.builder()
                        .percent(13)
                        .percentBColor("success")
                        .build())
                .description("Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam rem officia, corrupti reiciendis minima nisi modi, quasi, odio minus dolore impedit fuga eum eligendi.")
                .category("Baking material")
                .populate("Recently Added")
                .image(Image.builder()
                        .imgBack("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-2-min.jpg")
                        .imgFront("https://themepanthers.com/wp/nest/d1/wp-content/uploads/2022/05/product-20-4-min.jpg")
                        .build())
                .build();
        return List.of(
                item1,
                item2,
                item3,
                item4,
                item5,
                item6,
                item7,
                item8,
                item9,
                item10,
                item11,
                item12,
                item13,
                item14,
                item15,
                item16);
    }
}
